'use client';
import type { Meal } from '@diet/shared';
import { Copy, Pencil, Plus, Trash2 } from 'lucide-react';
import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiFetch, jsonRequest } from '@/lib/api/client';
import { EmptyState, ErrorState, Loading } from '@/components/ui';
export default function MealsPage(){const qc=useQueryClient();const meals=useQuery({queryKey:['meals'],queryFn:()=>apiFetch<Meal[]>('/meals')});const action=useMutation({mutationFn:({id,type}:{id:string;type:'delete'|'duplicate'})=>apiFetch(type==='delete'?`/meals/${id}`:`/meals/${id}/duplicate`,jsonRequest(type==='delete'?'DELETE':'POST')),onSuccess:()=>qc.invalidateQueries({queryKey:['meals']})});return <><header className="mb-6 flex items-end justify-between"><div><h1 className="page-title">Meals</h1><p className="muted mt-2">Reusable groups of foods.</p></div><Link className="btn btn-primary" href="/meals/new"><Plus size={18}/>New meal</Link></header>{action.error&&<div className="mb-4"><ErrorState error={action.error}/></div>}{meals.isLoading?<Loading/>:meals.error?<ErrorState error={meals.error}/>:meals.data?.length?<div className="grid gap-3 md:grid-cols-2">{meals.data.map(meal=><article className="card p-5" key={meal.id}><h2 className="text-lg font-black">{meal.name}</h2><p className="muted mt-1 text-sm">{meal.items.length} foods · {meal.calories} kcal</p><p className="muted mt-3 text-xs">Protein {meal.protein}g · Carbs {meal.carbs}g · Fat {meal.fat}g</p><div className="mt-4 flex gap-2"><Link className="btn btn-secondary" href={`/meals/${meal.id}/edit`}><Pencil size={16}/>Edit</Link><button className="btn btn-secondary" onClick={()=>action.mutate({id:meal.id,type:'duplicate'})}><Copy size={16}/></button><button className="btn btn-danger" onClick={()=>action.mutate({id:meal.id,type:'delete'})}><Trash2 size={16}/></button></div></article>)}</div>:<EmptyState title="No meals yet" body="Create a reusable meal from your foods."/>}</>}

