'use client';
import type { Food } from '@diet/shared';
import { Copy, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiFetch, jsonRequest } from '@/lib/api/client';
import { EmptyState, ErrorState, Loading } from '@/components/ui';
export default function FoodsPage(){const [search,setSearch]=useState('');const qc=useQueryClient();const foods=useQuery({queryKey:['foods',search],queryFn:()=>apiFetch<Food[]>(`/foods?search=${encodeURIComponent(search)}`)});const action=useMutation({mutationFn:({id,type}:{id:string;type:'delete'|'duplicate'})=>apiFetch(type==='delete'?`/foods/${id}`:`/foods/${id}/duplicate`,jsonRequest(type==='delete'?'DELETE':'POST')),onSuccess:()=>qc.invalidateQueries({queryKey:['foods']})});return <><header className="mb-6 flex items-end justify-between"><div><h1 className="page-title">Foods</h1><p className="muted mt-2">System staples and your private foods.</p></div><Link className="btn btn-primary" href="/foods/new"><Plus size={18}/>New food</Link></header><div className="card mb-4 flex items-center gap-2 p-3"><Search className="text-slate-400" size={19}/><input className="w-full outline-none" placeholder="Search foods" value={search} onChange={e=>setSearch(e.target.value)}/></div>{action.error&&<div className="mb-4"><ErrorState error={action.error}/></div>}{foods.isLoading?<Loading/>:foods.error?<ErrorState error={foods.error}/>:foods.data?.length?<div className="card overflow-hidden"><div className="divide-y divide-slate-100">{foods.data.map(food=><div className="flex items-center gap-4 p-4" key={food.id}><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate">{food.name}</strong><span className={`rounded px-2 py-0.5 text-[10px] font-black ${food.canEdit?'bg-blue-50 text-blue-700':'bg-green-50 text-green-700'}`}>{food.canEdit?'MY FOOD':'SYSTEM'}</span></div><p className="muted mt-1 text-sm">{food.servingSize} {food.servingUnit.toLowerCase()} · {food.calories} kcal · P {food.protein} · C {food.carbs} · F {food.fat}</p></div>{food.canEdit?<><Link aria-label={`Edit ${food.name}`} className="btn btn-secondary" href={`/foods/${food.id}/edit`}><Pencil size={16}/></Link><button aria-label={`Delete ${food.name}`} className="btn btn-danger" onClick={()=>action.mutate({id:food.id,type:'delete'})}><Trash2 size={16}/></button></>:<button className="btn btn-secondary" onClick={()=>action.mutate({id:food.id,type:'duplicate'})}><Copy size={16}/>Copy to my foods</button>}</div>)}</div></div>:<EmptyState title="No foods found" body="Try another search or create a private food."/>}</>}

